local camera = require "orthographic.camera"

-- Constants

local zoom = 1
local offset = 40

-- Hashed values

local camera_id = hash("/camera")
local player_id = hash("/player")

function init(self)
	-- Configure camera
	msg.post(camera_id, "follow", 
	{ target = player_id, horizontal = false, lerp = 0.1, offset = vmath.vector3(0, offset, 0) })	
	msg.post(camera_id, "zoom_to", { zoom = zoom })
	msg.post(camera_id, "use_projection", { projection = hash("FIXED_AUTO") })
end